services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mylc
    ports:
      - "5432:5432"
    volumes:
      - mylc_db:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  api:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mylc?sslmode=disable
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mylc_db: